In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
%pwd

'/content/drive/My Drive/DataSets_googleCollab'

In [ ]:
%ls

drive/  sample_data/


In [ ]:
%cd '/content/drive/MyDrive/DataSets_googleCollab'

/content/drive/MyDrive/DataSets_googleCollab


In [ ]:
!unzip train.csv.zip

Archive:  train.csv.zip
replace train.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: train.csv               


In [ ]:
import numpy as np
import pylab as pl
import pandas as pd
import matplotlib.pyplot as plt 
%matplotlib inline
import seaborn as sns
from sklearn.utils import shuffle
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix,classification_report
from sklearn.model_selection import cross_val_score, GridSearchCV
# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list the files in the input directory

import os
#print(os.listdir("../input"))

# Any results you write to the current directory are saved as output.

In [ ]:
%pwd

'/content/drive/MyDrive/DataSets_googleCollab'

In [ ]:
train = pd.read_csv("train.csv")
#test = pd.read_csv("../input/predict-who-is-more-influential-in-a-social-network/test.csv")

In [ ]:
train.info()
train[0:10]

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5500 entries, 0 to 5499
Data columns (total 23 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Choice               5500 non-null   int64  
 1   A_follower_count     5500 non-null   int64  
 2   A_following_count    5500 non-null   int64  
 3   A_listed_count       5500 non-null   int64  
 4   A_mentions_received  5500 non-null   float64
 5   A_retweets_received  5500 non-null   float64
 6   A_mentions_sent      5500 non-null   float64
 7   A_retweets_sent      5500 non-null   float64
 8   A_posts              5500 non-null   float64
 9   A_network_feature_1  5500 non-null   int64  
 10  A_network_feature_2  5500 non-null   float64
 11  A_network_feature_3  5500 non-null   float64
 12  B_follower_count     5500 non-null   int64  
 13  B_following_count    5500 non-null   int64  
 14  B_listed_count       5500 non-null   int64  
 15  B_mentions_received  5500 non-null   f

Choice  A_follower_count  A_following_count  A_listed_count  \
0       0               228                302               3   
1       0             21591               1179             228   
2       0              7310               1215             101   
3       0                20                  7               2   
4       1             45589                862            2641   
5       0            285735             276251            3417   
6       0            285735             276251            3417   
7       1              9512                 12             213   
8       1           2273871               4524           11946   
9       0            182598               1402            3831   

   A_mentions_received  A_retweets_received  A_mentions_sent  A_retweets_sent  \
0             0.583979             0.100503         0.100503         0.100503   
1            90.456506            25.798292         5.709329         1.111159   
2            25.503644             9.556347         5.361519         0.591206   
3             7.690824             0.277306         1.331508         0.100503   
4           148.854279            36.998884        27.881768         3.333492   
5            19.327582             7.292016         0.100503         0.100503   
6            19.327582             7.292016         0.100503         0.100503   
7            52.167068            23.182288         0.362150         0.100503   
8          6782.405338          2944.524245        12.955723         2.791861   
9           145.844910            74.002958        23.549189         0.100503   

     A_posts  A_network_feature_1  ...  B_following_count  B_listed_count  \
0   0.362150                    2  ...              29808            1689   
1   5.176620                  369  ...                848            1610   
2   3.589718                   95  ...                482             206   
3   2.830627                    6  ...              17637             278   
4  23.861282                  551  ...               1711             181   
5   0.100503                   60  ...               1500             474   
6   0.100503                   60  ...               1001           15117   
7   6.806045                  195  ...                710             959   
8  66.206208                21678  ...                551            6209   
9  15.953243                  567  ...               1299            9950   

   B_mentions_received  B_retweets_received  B_mentions_sent  B_retweets_sent  \
0            15.430498             3.984029         8.204331         0.332423   
1            40.495021             8.943607         3.227677         0.564343   
2             0.734696             0.354379         0.603202         0.100503   
3           572.874856           390.293681        27.552040         7.167557   
4            21.601866             3.581661         6.764657         1.119727   
5            40.592512             5.923009        19.648064         1.861765   
6           266.013874            54.345230        13.111904         0.334766   
7             7.368643             2.088375         1.598798         0.595812   
8           493.256379           206.660552         4.115212         0.854539   
9           189.755230            67.310223        11.294831         2.567269   

     B_posts  B_network_feature_1  B_network_feature_2  B_network_feature_3  
0   6.988815                   66            75.530303          1916.893939  
1   1.070321                  163           132.030675          2931.515337  
2   0.603202                    3            10.333333           277.333333  
3  32.101906                 1762            23.469296          1395.845634  
4   4.563246                   85            48.500000          1993.627907  
5  12.261029                  128           107.431818          2481.136364  
6  13.665173                  928           172.986229          5321.646186  
7   1.332849        

Group the Choice and A_follower_count, then get the max, min, and mean of A_posts

In [ ]:
display(train[["Choice","A_follower_count","A_posts",]].groupby(["Choice","A_follower_count"]).agg(["min",'mean',"max"]).style.background_gradient(cmap="autumn"))

In [ ]:
"""test.info()
test[0:10]"""

'test.info()\ntest[0:10]'

In [ ]:
print("Any missing sample in training set:",train.isnull().values.any())
#print("Any missing sample in test set:",test.isnull().values.any(), "\n")

Any missing sample in training set: False


In [ ]:
#Frequency distribution of classes"
train_outcome = pd.crosstab(index=train["Choice"],  # Make a crosstab
                              columns="count")      # Name the count column

train_outcome

col_0   count
Choice       
0        2698
1        2802

In [ ]:
#Select feature column names and target variable we are going to use for training
features=['A_follower_count','A_listed_count','A_mentions_received','A_retweets_received','A_posts','A_network_feature_1','A_network_feature_2','A_network_feature_3','B_follower_count','B_following_count','B_listed_count','B_mentions_received','B_retweets_received','B_posts','B_network_feature_1','B_network_feature_2','B_network_feature_3']
target = 'Choice'

In [ ]:
#This is input which our classifier will use as an input.
train[features].head(10)

A_follower_count  A_listed_count  A_mentions_received  A_retweets_received  \
0               228               3             0.583979             0.100503   
1             21591             228            90.456506            25.798292   
2              7310             101            25.503644             9.556347   
3                20               2             7.690824             0.277306   
4             45589            2641           148.854279            36.998884   
5            285735            3417            19.327582             7.292016   
6            285735            3417            19.327582             7.292016   
7              9512             213            52.167068            23.182288   
8           2273871           11946          6782.405338          2944.524245   
9            182598            3831           145.844910            74.002958   

     A_posts  A_network_feature_1  A_network_feature_2  A_network_feature_3  \
0   0.362150                    2           166.500000         11355.000000   
1   5.176620                  369            18.442971          1330.366048   
2   3.589718                   95            68.927835          5999.896907   
3   2.830627                    6             2.000000            96.166667   
4  23.861282                  551           127.404293          2833.847943   
5   0.100503                   60            44.806452          4144.258065   
6   0.100503                   60            44.806452          4144.258065   
7   6.806045                  195            11.678571           564.040816   
8  66.206208                21678             6.859364          1113.202016   
9  15.953243                  567           276.496516          8038.066202   

   B_follower_count  B_following_count  B_listed_count  B_mentions_received  \
0             34463              29808            1689            15.430498   
1             39262                848            1610            40.495021   
2              3622                482             206             0.734696   
3             19562              17637             278           572.874856   
4              7554               1711             181            21.601866   
5             11147               1500             474            40.592512   
6            185616               1001           15117           266.013874   
7              8120                710             959             7.368643   
8            298668                551            6209           493.256379   
9            117913               1299            9950           189.755230   

   B_retweets_received    B_posts  B_network_feature_1  B_network_feature_2  \
0             3.984029   6.988815                   66            75.530303   
1             8.943607   1.070321                  163           132.030675   
2             0.354379   0.603202                    3            10.333333   
3           390.293681  32.101906                 1762            23.469296   
4             3.581661   4.563246                   85            48.500000   
5             5.923009  12.261029                  128           107.431818   
6            54.345230  13.665173                  928           172.986229   
7             2.088375   1.332849                   29           205.533333   
8           206.660552   3.075463                 2021            75.970098   
9            67.310223  10.933766                  791           185.542033   

   B_network_feature_3  
0          1916.893939  
1          2931.515337  
2           277.333333  
3          1395.845634  
4          1993.627907  
5          2481.136364  
6          5321.646186  
7          4302.466667  
8          3865.446569  
9          5535.939774

In [ ]:
#Display first 10 target variables
train[target].head(10).values

array([0, 0, 0, 0, 1, 0, 0, 1, 1, 0])

In [ ]:
X=train.drop([target], axis=1)
y=train[target]

In [ ]:

from sklearn.model_selection import train_test_split

#Split dataset into train and test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.4)


# **KNeighborsClassifier**

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 9, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)


KNeighborsClassifier(n_neighbors=9)

In [ ]:
#Make predictions using the features from the test data set
predictions = classifier.predict( X_test)

#Display our predictions
predictions

array([1, 1, 0, ..., 1, 1, 0])

In [ ]:
import sklearn
#print(sklearn.__version__)
from sklearn.metrics import confusion_matrix
sklearn.metrics.confusion_matrix(y_test,predictions)

array([[802, 291],
       [256, 851]])

In [ ]:
#from sklearn.metrics import accuracy_score
accuracy_score(y_test, predictions)

0.7513636363636363

# **Support Vector Machine**

In [ ]:
from sklearn.svm import SVC
classifier = SVC(kernel='rbf', random_state = 1)
"""classifier.fit(train[features],train[target])

#Make predictions using the features from the test data set
predictions = classifier.predict(test[features])

#Display our predictions
predictions
"""
classifier.fit(X_train, y_train)


SVC(random_state=1)

In [ ]:
#Make predictions using the features from the test data set
predictions_svm = classifier.predict( X_test)

#Display our predictions
predictions_svm

array([1, 1, 1, ..., 1, 1, 1])

In [ ]:
import sklearn
print(sklearn.__version__)
from sklearn.metrics import confusion_matrix
sklearn.metrics.confusion_matrix(y_test,predictions_svm)

1.0.2


array([[622, 471],
       [169, 938]])

In [ ]:
from sklearn.metrics import accuracy_score

#accuracy_score(y_test, predictions_svm)

# **RandomForestClassifier**

In [ ]:
from sklearn.ensemble import RandomForestClassifier

# We define the model
rfcla = RandomForestClassifier(n_estimators=100,random_state=168,n_jobs=-1)

# We train model
#rfcla.fit(train[features],train[target])
rfcla.fit(X_train, y_train)


RandomForestClassifier(n_jobs=-1, random_state=168)

In [ ]:
#Make predictions using the features from the test data set
predictions_rfcla = classifier.predict( X_test)

#Display our predictions
predictions_rfcla

array([1, 1, 1, ..., 1, 1, 1])

In [ ]:
import sklearn
print(sklearn.__version__)
from sklearn.metrics import confusion_matrix
sklearn.metrics.confusion_matrix(y_test,predictions_rfcla)

1.0.2


array([[622, 471],
       [169, 938]])

In [ ]:
from sklearn.metrics import accuracy_score

#accuracy_score(y_test, predictions_rfcla)